name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install pip==21.0
          pip install easyocr pillow numpy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
      - name: run
        run: STD_ID='${{ secrets.STD_ID }}' PASSWORD='${{ secrets.PASSWORD }}' python3 main.py
